#ifndef CONSTANTS_H
#define CONSTANTS_H

enum CONSTANTS
{
    WIDTH = 450,
    HEIGHT = 600,
    PADDLE_HEIGHT = 16,
    RECT_PADDLE_WIDTH = 50,
    Y_FOR_PADDLE = 584, //HEIGHT - PADDLE_HEIGHT
    X_LEFT_PADDLE_CIRCL = 33, // PADDLE_WIDTH/2 + PADDLE_HEIGHT/2
    X_RIGHT_PADDLE_CIRCL = 17, // PADDLE_WIDTH/2 - PADDLE_HEIGHT/2 - 1
    BALL_DIAMETER = 10,
    BRICK_HEIGHT = 12,
    RECT_BRICK_WIDTH = 50,
    ALL_BRICK_WIDTH = 62
};

enum SURFACES
{
    NONE = -1,
    LEFT_WALL = 0,
    RIGHT_WALL = 1,
    CELLING = 2,
    LEFT_CORNER = 3,
    RIGHT_CORNER = 4,
    PADDLE = 5,
    BOTTOM = 6,
    BRICK_TOP = 7,
    BRICK_BOTTOM = 8
};

#endif // CONSTANTS_H
